version: "3.7"
services:
    web:
      build:
        context: .
      ports:
        - '8080:8080'
      depends_on:
        - database
      volumes:
        - ./:/usr/src/app
    database:
        - mongo
        - ports:
        - '27017:27017'