version: "3.7"
services:
    web:
      build:
        context: .
      ports:
        - '8080:8080'
      depends_on:
        - mongo
      volumes:
        - ./:/usr/src/app
    mongo:
      image: mongo
      ports:
        - '27017:27017'