version: "3.7"
services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: reddit-clone
      image: reddit-clone
      env_file: .env
      ports:
        - '8080:8080'
      links: 
        - mongo
      depends_on:
        - mongo
      environment:
        WAIT_HOSTS: mongo:27017
    #   volumes:
    #     - ./:/usr/src/app
    
    mongo:
      container_name: mongo
      image: mongo
      env_file: .env
      ports:
        - '27017:27017'

volumes: 
  mongo_data: